name: awesome_dio_interceptor
description: A simple dio log interceptor (mainly inspired by the built-in dio LogInterceptor), which has coloring features and json formatting so you can have a better readable output.
version: 1.1.0
homepage: https://github.com/devmuaz/awesome_dio_interceptor

environment:
  sdk: ^3.3.0

dependencies:
  dio: ^5.4.0
  colorize: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
